[project]
name = "odoo-addons-oca-stock-logistics-request"
version = "18.0.20241113.0"
dependencies = [
    "odoo-addon-stock_request==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
